spring.application.name=ledger-core

spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_core
spring.datasource.username=ledger_user
spring.datasource.password=ledger_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true