spring.application.name=ledger-core
spring.autoconfigure.exclude=\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration,\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration